---
# rancher-play.yml
# Based on https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-manual-setup/
# Example run: ansible-playbook -i hosts rancher-play.yml

# just need to replicate this in ansible-speak:
# sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher
- hosts: all
  become: true
  vars:
#    rancher_http_port: "80:80"
#    rancher_https_port: "443:433"

  tasks:
  - name: Install Rancher on remote server
    docker_container:
      name: rancher
      image: rancher/rancher
      privileged: yes
      restart_policy: unless-stopped
      ports:
        - 80:80
        - 443:443